const tickets=[
 {id:'LAB-2026-0018',title:'Projetor sem imagem',category:'Projetor ou áudio',status:'Aguardando',teacher:'Mariana Lopes',lab:'LabInfo 02',time:'Hoje, 14:32',technician:'Não atribuído',description:'O projetor liga, mas não exibe a imagem do computador do professor.'},
 {id:'LAB-2026-0017',title:'Computador 08 não inicia',category:'Computador não liga',status:'Em atendimento',teacher:'Carlos Henrique',lab:'LabInfo 01',time:'Hoje, 13:48',technician:'Rafael Souza',description:'Ao pressionar o botão, a luz acende por alguns segundos e o computador desliga.'},
 {id:'LAB-2026-0016',title:'Sem acesso à internet',category:'Internet ou rede',status:'Aguardando',teacher:'Patrícia Alves',lab:'LabInfo 04',time:'Hoje, 11:20',technician:'Não atribuído',description:'Vários computadores estão conectados à rede, porém sem acesso à internet.'},
 {id:'LAB-2026-0015',title:'Instalação do QGIS',category:'Software ou acesso',status:'Resolvido',teacher:'João Mendes',lab:'LabInfo 03',time:'Hoje, 09:05',technician:'Ana Costa',description:'Necessária instalação do QGIS para a aula prática da próxima semana.'}
];
const $=s=>document.querySelector(s); let selected=tickets[0];
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3200)}
function badge(status){const c=status==='Aguardando'?'waiting':status==='Em atendimento'?'active':'done';return `<span class="badge ${c}">${status}</span>`}
function renderTickets(){const q=$('#ticketSearch').value.toLowerCase(),filter=$('#statusFilter').value;const rows=tickets.filter(t=>(filter==='Todos os status'||t.status===filter)&&Object.values(t).join(' ').toLowerCase().includes(q));$('#ticketList').innerHTML=rows.map(t=>`<article class="ticket-row ${selected.id===t.id?'active':''}" data-id="${t.id}"><div><span class="ticket-id">${t.id}</span><h3>${t.title}</h3><div class="ticket-meta"><span>● ${t.teacher}</span><span>▣ ${t.lab}</span><span>◷ ${t.time}</span></div></div>${badge(t.status)}</article>`).join('')||'<p style="padding:30px;color:#66736b">Nenhum chamado encontrado.</p>';document.querySelectorAll('.ticket-row').forEach(r=>r.onclick=()=>{selected=tickets.find(t=>t.id===r.dataset.id);renderTickets();renderDetail()})}
function renderDetail(){const t=selected;$('#ticketDetail').innerHTML=`<div class="detail-top"><div><span class="ticket-id">${t.id}</span><h2>${t.title}</h2></div>${badge(t.status)}</div><div class="detail-data"><div><small>Professor</small><strong>${t.teacher}</strong></div><div><small>Laboratório</small><strong>${t.lab}</strong></div><div><small>Categoria</small><strong>${t.category}</strong></div><div><small>Abertura</small><strong>${t.time}</strong></div></div><p class="description-box">${t.description}</p><label>Técnico responsável<select id="technician"><option>${t.technician}</option><option>Ana Costa</option><option>Rafael Souza</option><option>Paulo Lima</option></select></label><label>Resposta ao professor<textarea id="reply" placeholder="Escreva uma atualização sobre o atendimento..."></textarea></label><div class="detail-actions"><button class="secondary" id="assign">Atribuir</button><button class="primary" id="sendReply" style="margin:0">Enviar resposta</button></div>`;$('#assign').onclick=()=>{t.technician=$('#technician').value;t.status='Em atendimento';renderTickets();renderDetail();toast('Chamado atribuído com sucesso.')};$('#sendReply').onclick=()=>{if(!$('#reply').value.trim())return toast('Digite uma resposta antes de enviar.');toast('Resposta registrada. O docente receberá um e-mail.')};}
$('#adminToggle').onclick=()=>{const admin=$('#adminView').hidden;$('#adminView').hidden=!admin;$('#teacherView').hidden=admin;$('#adminToggle').textContent=admin?'Área docente':'Área técnica';if(admin){renderTickets();renderDetail()}window.scrollTo(0,0)};
$('#description').oninput=e=>$('#charCount').textContent=e.target.value.length;
$('#ticketForm').onsubmit=e=>{e.preventDefault();const email=$('#email').value.trim().toLowerCase();if(!email.endsWith('@ifms.edu.br'))return toast('Informe um e-mail institucional @ifms.edu.br.');const id=`LAB-2026-${String(19+tickets.length).padStart(4,'0')}`;toast(`Chamado ${id} aberto com sucesso!`);e.target.reset();$('#charCount').textContent='0'};
$('#protocolButton').onclick=()=>{const id=$('#protocolInput').value.trim().toUpperCase(),t=tickets.find(x=>x.id===id);$('#protocolResult').innerHTML=t?`<strong>${t.status}</strong><br>${t.title} • ${t.technician}`:'Protocolo não encontrado. Confira o ID informado.'};
$('#ticketSearch').oninput=renderTickets;$('#statusFilter').onchange=renderTickets;$('#newCategory').onclick=()=>toast('Cadastro de categorias será conectado ao Google Apps Script.');
renderTickets();renderDetail();
