(()=>{
  const sb=window.labinfoDb,$=selector=>document.querySelector(selector),safe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  if(!sb)return;
  const localIso=(date,time)=>new Date(`${date}T${time}:00-04:00`).toISOString(),localDate=value=>new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Cuiaba',dateStyle:'short'}).format(new Date(value)),localTime=value=>new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Cuiaba',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
  const normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
  const periods=[['07:00','12:35'],['13:00','18:35'],['18:45','22:50']],times=[];
  periods.forEach(([start,end])=>{let [hour,minute]=start.split(':').map(Number);while(hour*60+minute+45<=Number(end.slice(0,2))*60+Number(end.slice(3))){times.push(`${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`);minute+=45;hour+=Math.floor(minute/60);minute%=60}});
  $('#reservationTime').innerHTML='<option value="">Selecione o horário</option>'+times.map(time=>`<option value="${time}">${time}</option>`).join('');
  $('#reservationDate').min=new Date().toLocaleDateString('en-CA',{timeZone:'America/Cuiaba'});

  function showPublic(view,push=true){
    $('#homeView').hidden=view!=='home';$('#reservationsPublicView').hidden=view!=='reservations';$('#teacherView').hidden=view!=='support';$('#adminView').hidden=true;
    if(push)history.pushState({},'',view==='home'?'/labinfo/':view==='reservations'?'/labinfo/reservas/':'/labinfo/suporte/');window.scrollTo(0,0);
  }
  $('#openReservations').onclick=()=>showPublic('reservations');$('#backHome').onclick=()=>showPublic('home');
  $('.brand').addEventListener('click',event=>{if(!$('#adminView').hidden)return;event.preventDefault();showPublic('home')});
  window.addEventListener('popstate',()=>{const path=location.pathname;if(path.includes('/reservas'))showPublic('reservations',false);else if(path.includes('/suporte'))showPublic('support',false);else if(!path.includes('/admin'))showPublic('home',false)});
  if(location.pathname.includes('/reservas')||new URLSearchParams(location.search).has('confirm_reservation'))showPublic('reservations',false);else if(location.pathname.includes('/suporte'))showPublic('support',false);

  let publicServer=null,publicLabs=[];
  async function loadPublicLabs(){const {data,error}=await sb.from('labs').select('id,name,code').eq('active',true).order('name');if(error)return;publicLabs=data||[];$('#reservationLab').innerHTML='<option value="">Selecione o laboratório</option>'+publicLabs.map(lab=>`<option value="${lab.id}">${safe(lab.name)}</option>`).join('')}
  let identityTimer;
  $('#reservationSiape').oninput=()=>{clearTimeout(identityTimer);publicServer=null;$('#reservationIdentity').textContent='Validando cadastro…';identityTimer=setTimeout(async()=>{const siape=$('#reservationSiape').value.trim();if(siape.length<5){$('#reservationIdentity').textContent='Digite seu SIAPE para validação.';return}const {data,error}=await sb.rpc('identify_server',{p_siape:siape});publicServer=data?.[0]||null;$('#reservationIdentity').textContent=error||!publicServer?'Servidor não localizado ou cadastro inativo.':`${publicServer.full_name} • ${publicServer.email}`;$('#reservationIdentity').className='field-hint '+(publicServer?'found':'pending')},350)};
  $('#reservationDate').onchange=()=>{const date=new Date($('#reservationDate').value+'T12:00:00');if(date.getDay()===0){$('#reservationDate').value='';toast('Os laboratórios não recebem reservas aos domingos.')}};
  $('#reservationRecurrence').onchange=()=>{const weekly=$('#reservationRecurrence').value==='weekly';$('#reservationUntilLabel').hidden=!weekly;$('#reservationUntil').required=weekly;$('#reservationUntil').min=$('#reservationDate').value};
  $('#publicReservationForm').onsubmit=async event=>{event.preventDefault();if(!publicServer)return toast('Valide um SIAPE cadastrado antes de continuar.');const button=event.submitter;button.disabled=true;button.textContent='Registrando solicitação…';try{const recurrence=$('#reservationRecurrence').value,{data,error}=await sb.rpc('create_public_reservation',{p_siape:$('#reservationSiape').value.trim(),p_lab:$('#reservationLab').value,p_subject:$('#reservationSubject').value.trim(),p_start:localIso($('#reservationDate').value,$('#reservationTime').value),p_blocks:Number($('#reservationBlocks').value),p_notes:$('#reservationNotes').value.trim()||null,p_recurrence:recurrence,p_until:recurrence==='weekly'?$('#reservationUntil').value:null});if(error)throw error;event.target.reset();$('#reservationUntilLabel').hidden=true;publicServer=null;$('#reservationIdentity').textContent='Digite seu SIAPE para validação.';toast(`Solicitação ${data?.[0]?.protocol||''} registrada. Confirme pelo e-mail institucional.`)}catch(error){toast(error.message||'Não foi possível solicitar a reserva.')}finally{button.disabled=false;button.innerHTML='Solicitar reserva <span>→</span>'}};
  async function searchMyReservations(){const box=$('#myReservationsResult'),siape=$('#reservationSearchSiape').value.trim();box.innerHTML='<p class="empty">Consultando…</p>';const {data,error}=await sb.rpc('my_reservations',{p_siape:siape});if(error){box.innerHTML=`<p class="error-text">${safe(error.message)}</p>`;return}box.innerHTML=(data||[]).map(item=>`<article class="public-reservation-item"><header><strong>${safe(item.protocol)}</strong><span class="reservation-status status-${normalize(item.status).replace(/\s/g,'-')}">${safe(item.status)}</span></header><h3>${safe(item.subject)}</h3><p>${safe(item.lab)} • ${localDate(item.starts_at)}, ${localTime(item.starts_at)}–${localTime(item.ends_at)}</p>${item.reason?`<small>${safe(item.reason)}</small>`:''}</article>`).join('')||'<p class="empty">Nenhuma reserva encontrada para este SIAPE.</p>'}
  $('#searchReservations').onclick=searchMyReservations;$('#reservationSearchSiape').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();searchMyReservations()}};
  async function confirmFromLink(){const token=new URLSearchParams(location.search).get('confirm_reservation');if(!token)return;const box=$('#reservationConfirmation');box.hidden=false;box.innerHTML='<strong>Confirmando sua reserva…</strong>';const {data,error}=await sb.rpc('confirm_reservation',{p_token:token});box.innerHTML=error?`<strong>Não foi possível confirmar</strong><p>${safe(error.message)}</p>`:`<strong>✓ Reserva ${safe(data?.[0]?.protocol)} confirmada</strong><p>A solicitação foi encaminhada para autorização da equipe.</p>`;history.replaceState({},'',location.pathname)}

  const admin=$('#adminView');admin.insertAdjacentHTML('beforeend',`<section id="reservationsSection" class="admin-section reservations-admin" hidden>
    <div class="reservation-toolbar card"><div><button id="reservationPrevWeek" class="secondary" type="button">←</button><button id="reservationToday" class="secondary" type="button">Hoje</button><button id="reservationNextWeek" class="secondary" type="button">→</button><strong id="reservationWeekLabel"></strong></div><label>Laboratório<select id="adminReservationLab"></select></label><button id="newReservationButton" class="primary" type="button">+ Nova reserva</button><button id="csvReservationButton" class="secondary" type="button">Importar CSV</button></div>
    <div id="reservationStats" class="reservation-stats"></div><section class="card reservation-calendar-wrap"><div id="reservationCalendar" class="reservation-calendar"></div></section>
    <section class="card reservation-list-card"><div class="registry-head"><div><h2>Solicitações e reservas</h2><span id="reservationCount"></span></div><input id="reservationAdminSearch" placeholder="Buscar professor, disciplina ou protocolo"></div><div id="reservationAdminList"></div></section>
  </section>
  <div id="reservationModal" class="modal-backdrop" hidden><form id="staffReservationForm" class="modal card"><button class="modal-close" type="button" aria-label="Fechar">×</button><span class="eyebrow">NOVA RESERVA</span><h2>Cadastrar reserva</h2><label>Servidor<select id="staffReservationServer" required></select></label><label>Laboratório<select id="staffReservationLab" required></select></label><label>Disciplina ou atividade<input id="staffReservationSubject" maxlength="160" required></label><div class="field-row"><label>Data inicial<input id="staffReservationDate" type="date" required></label><label>Hora<select id="staffReservationTime" required></select></label></div><label>Duração<select id="staffReservationBlocks"><option value="1">45 minutos</option><option value="2">1h30</option><option value="3">2h15</option><option value="4">3h</option></select></label><div class="field-row"><label>Repetição<select id="staffReservationRecurrence"><option value="none">Somente nesta data</option><option value="weekly">Semanalmente, no mesmo dia</option></select></label><label id="staffReservationUntilLabel" hidden>Repetir até<input id="staffReservationUntil" type="date"></label></div><label>Observações<textarea id="staffReservationNotes" rows="3"></textarea></label><button class="primary" type="submit">Cadastrar e autorizar</button></form></div>
  <div id="reservationCsvModal" class="modal-backdrop" hidden><section class="modal card csv-reservation-modal"><button class="modal-close" type="button" aria-label="Fechar">×</button><span class="eyebrow">IMPORTAÇÃO EM LOTE</span><h2>Importar reservas por CSV</h2><p>Colunas obrigatórias: <strong>Data, Hora, Disciplina, Professor</strong>. Para repetir no semestre, use também <strong>Data fim</strong> e <strong>Recorrência</strong> com o valor <em>semanal</em>.</p><label>Laboratório para este lote<select id="csvReservationLab" required></select></label><label>Arquivo CSV<input id="reservationCsvFile" type="file" accept=".csv,text/csv"></label><div id="reservationCsvPreview"></div><button id="importReservationsCsv" class="primary" type="button" disabled>Importar reservas válidas</button></section></div>`);

  let reservations=[],adminLabs=[],adminServers=[],weekStart=getMonday(new Date()),draggedReservation=null,reservationChannel=null;
  function getMonday(value){const date=new Date(value);date.setHours(12,0,0,0);const day=date.getDay()||7;date.setDate(date.getDate()-day+1);return date}
  const isoDate=date=>date.toLocaleDateString('en-CA',{timeZone:'America/Cuiaba'}),addDays=(date,days)=>{const copy=new Date(date);copy.setDate(copy.getDate()+days);return copy};
  async function loadReservationAdmin(){const [{data:r,error},{data:l},{data:s}]=await Promise.all([sb.from('reservations').select('*,servers(full_name,siape,email),labs(name,code)').order('starts_at'),sb.from('labs').select('id,name,code').eq('active',true).order('name'),sb.from('servers').select('id,full_name,siape,email').eq('active',true).order('full_name')]);if(error)return toast(error.message);reservations=r||[];adminLabs=l||[];adminServers=s||[];fillAdminOptions();renderReservationAdmin()}
  function fillAdminOptions(){const labOptions=adminLabs.map(lab=>`<option value="${lab.id}">${safe(lab.name)}</option>`).join('');['adminReservationLab','staffReservationLab','csvReservationLab'].forEach(id=>{const element=$('#'+id),value=element.value;element.innerHTML=labOptions;if(value)element.value=value});$('#staffReservationServer').innerHTML=adminServers.map(server=>`<option value="${server.id}">${safe(server.full_name)} • ${safe(server.siape)}</option>`).join('');$('#staffReservationTime').innerHTML=times.map(time=>`<option value="${time}">${time}</option>`).join('')}
  function renderReservationAdmin(){renderCalendar();renderReservationList();const counts={pending:reservations.filter(r=>r.status.includes('Aguardando')).length,authorized:reservations.filter(r=>r.status==='Autorizada').length,cancelled:reservations.filter(r=>r.status==='Cancelada').length};$('#reservationStats').innerHTML=`<article><small>Aguardando</small><strong>${counts.pending}</strong></article><article><small>Autorizadas</small><strong>${counts.authorized}</strong></article><article><small>Canceladas</small><strong>${counts.cancelled}</strong></article>`}
  function renderCalendar(){const labId=$('#adminReservationLab').value||adminLabs[0]?.id;if(labId&&!$('#adminReservationLab').value)$('#adminReservationLab').value=labId;const days=Array.from({length:6},(_,index)=>addDays(weekStart,index));$('#reservationWeekLabel').textContent=`${localDate(days[0])} a ${localDate(days[5])}`;let html='<div class="calendar-corner">Horário</div>'+days.map(day=>`<div class="calendar-day"><strong>${day.toLocaleDateString('pt-BR',{weekday:'short'})}</strong><span>${day.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</span></div>`).join('');times.forEach(time=>{html+=`<div class="calendar-time">${time}</div>`;days.forEach(day=>{const date=isoDate(day),items=reservations.filter(r=>r.lab_id===labId&&r.status!=='Cancelada'&&isoDate(new Date(r.starts_at))===date&&localTime(r.starts_at)===time);html+=`<div class="calendar-cell" data-date="${date}" data-time="${time}">${items.map(r=>`<article class="calendar-reservation status-${normalize(r.status).replace(/\s/g,'-')}" draggable="true" data-id="${r.id}" title="Arraste para alterar data ou horário"><strong>${safe(r.subject)}</strong><span>${safe(r.servers?.full_name)}</span><small>${localTime(r.starts_at)}–${localTime(r.ends_at)}</small></article>`).join('')}</div>`})});$('#reservationCalendar').innerHTML=html;$('#reservationCalendar').querySelectorAll('.calendar-reservation').forEach(card=>card.ondragstart=()=>{draggedReservation=reservations.find(r=>r.id===card.dataset.id)});$('#reservationCalendar').querySelectorAll('.calendar-cell').forEach(cell=>{cell.ondragover=event=>{event.preventDefault();cell.classList.add('drag-over')};cell.ondragleave=()=>cell.classList.remove('drag-over');cell.ondrop=async event=>{event.preventDefault();cell.classList.remove('drag-over');if(!draggedReservation)return;const {error}=await sb.rpc('staff_update_reservation',{p_id:draggedReservation.id,p_start:localIso(cell.dataset.date,cell.dataset.time),p_lab:labId,p_status:null,p_reason:null});draggedReservation=null;if(error)return toast(error.message);toast('Reserva reagendada e servidor notificado.');await loadReservationAdmin()}})}
  function renderReservationList(){const query=normalize($('#reservationAdminSearch').value),rows=reservations.filter(r=>!query||normalize([r.protocol,r.subject,r.servers?.full_name,r.labs?.name,r.status].join(' ')).includes(query));$('#reservationCount').textContent=`${rows.length} registro(s)`;$('#reservationAdminList').innerHTML=rows.map(r=>`<article class="reservation-admin-row"><div><span class="ticket-id">${safe(r.protocol)}</span><h3>${safe(r.subject)}</h3><p>${safe(r.servers?.full_name)} • ${safe(r.labs?.name)} • ${localDate(r.starts_at)}, ${localTime(r.starts_at)}–${localTime(r.ends_at)}</p></div><span class="reservation-status status-${normalize(r.status).replace(/\s/g,'-')}">${safe(r.status)}</span><div class="reservation-row-actions">${r.status==='Aguardando autorização'?`<button data-approve="${r.id}">Autorizar</button>`:''}${r.status!=='Cancelada'?`<button data-cancel="${r.id}">Cancelar</button>`:''}</div></article>`).join('')||'<p class="empty">Nenhuma reserva encontrada.</p>';$('#reservationAdminList').querySelectorAll('[data-approve]').forEach(button=>button.onclick=()=>updateStatus(button.dataset.approve,'Autorizada'));$('#reservationAdminList').querySelectorAll('[data-cancel]').forEach(button=>button.onclick=()=>{const reason=prompt('Informe o motivo do cancelamento:');if(reason)updateStatus(button.dataset.cancel,'Cancelada',reason)})}
  async function updateStatus(id,status,reason=null){const {error}=await sb.rpc('staff_update_reservation',{p_id:id,p_start:null,p_lab:null,p_status:status,p_reason:reason});if(error)return toast(error.message);toast(status==='Autorizada'?'Reserva autorizada e servidor notificado.':'Reserva cancelada e servidor notificado.');await loadReservationAdmin()}
  async function openReservationsAdmin(){document.querySelectorAll('.admin-section').forEach(section=>section.hidden=true);$('#reservationsSection').hidden=false;$('#adminTitle').textContent='Reservas dos laboratórios';$('#adminSubtitle').textContent='Organize a agenda, autorize solicitações e importe reservas em lote.';await loadReservationAdmin();if(!reservationChannel)reservationChannel=sb.channel('labinfo-reservations').on('postgres_changes',{event:'*',schema:'public',table:'reservations'},()=>loadReservationAdmin()).subscribe()}
  $('#reservationsMenuButton').onclick=openReservationsAdmin;$('#adminReservationLab').onchange=renderCalendar;$('#reservationAdminSearch').oninput=renderReservationList;$('#reservationPrevWeek').onclick=()=>{weekStart=addDays(weekStart,-7);renderCalendar()};$('#reservationNextWeek').onclick=()=>{weekStart=addDays(weekStart,7);renderCalendar()};$('#reservationToday').onclick=()=>{weekStart=getMonday(new Date());renderCalendar()};
  function modal(id,open){$('#'+id).hidden=!open;document.body.classList.toggle('modal-open',open)}
  $('#newReservationButton').onclick=()=>modal('reservationModal',true);$('#csvReservationButton').onclick=()=>modal('reservationCsvModal',true);document.querySelectorAll('#reservationModal .modal-close,#reservationCsvModal .modal-close').forEach(button=>button.onclick=()=>modal(button.closest('.modal-backdrop').id,false));
  $('#staffReservationRecurrence').onchange=()=>{const weekly=$('#staffReservationRecurrence').value==='weekly';$('#staffReservationUntilLabel').hidden=!weekly;$('#staffReservationUntil').required=weekly;$('#staffReservationUntil').min=$('#staffReservationDate').value};
  $('#staffReservationForm').onsubmit=async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{const recurrence=$('#staffReservationRecurrence').value,{data:created,error}=await sb.rpc('staff_create_reservation',{p_server:$('#staffReservationServer').value,p_lab:$('#staffReservationLab').value,p_subject:$('#staffReservationSubject').value.trim(),p_start:localIso($('#staffReservationDate').value,$('#staffReservationTime').value),p_blocks:Number($('#staffReservationBlocks').value),p_notes:$('#staffReservationNotes').value.trim()||null,p_source:'Equipe',p_recurrence:recurrence,p_until:recurrence==='weekly'?$('#staffReservationUntil').value:null});if(error)throw error;const notification=await sb.rpc('staff_update_reservation',{p_id:created.id,p_start:null,p_lab:null,p_status:'Autorizada',p_reason:null});if(notification.error)throw notification.error;event.target.reset();$('#staffReservationUntilLabel').hidden=true;modal('reservationModal',false);toast('Reserva cadastrada, autorizada e servidor notificado.');await loadReservationAdmin()}catch(error){toast(error.message)}finally{button.disabled=false}};
  let csvRows=[];
  function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean),delimiter=(lines[0].match(/;/g)||[]).length>=(lines[0].match(/,/g)||[]).length?';':',';const cells=line=>line.split(delimiter).map(value=>value.trim().replace(/^"|"$/g,'')),headers=cells(lines.shift()).map(normalize),parseDate=value=>{const parts=value.split(/[\/-]/);return parts[0]?.length===4?value:`${parts[2]}-${parts[1]?.padStart(2,'0')}-${parts[0]?.padStart(2,'0')}`};return lines.map((line,index)=>{const values=cells(line),get=name=>values[headers.indexOf(name)]||'',professor=get('professor')||get('nome completo')||get('nome'),server=adminServers.find(item=>normalize(item.full_name)===normalize(professor)),date=parseDate(get('data')),untilRaw=get('data fim')||get('fim'),until=untilRaw?parseDate(untilRaw):null,recurrence=normalize(get('recorrencia'))==='semanal'||until?'weekly':'none',time=(get('hora')||get('horario')).slice(0,5),subject=get('disciplina')||get('atividade'),errors=[];if(!server)errors.push('Professor não cadastrado');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))errors.push('Data inválida');if(recurrence==='weekly'&&!/^\d{4}-\d{2}-\d{2}$/.test(until||''))errors.push('Data final inválida');if(!times.includes(time))errors.push('Hora fora dos blocos');if(!subject)errors.push('Disciplina ausente');return {line:index+2,date,until,recurrence,time,subject,professor,server,errors}})}
  $('#reservationCsvFile').onchange=async event=>{const file=event.target.files[0];if(!file)return;csvRows=parseCsv(await file.text());$('#reservationCsvPreview').innerHTML=`<div class="csv-summary"><strong>${csvRows.filter(row=>!row.errors.length).length} válida(s)</strong><span>${csvRows.filter(row=>row.errors.length).length} com erro</span></div>`+csvRows.slice(0,50).map(row=>`<div class="csv-row ${row.errors.length?'invalid':''}"><span>Linha ${row.line}</span><strong>${safe(row.professor)}</strong><span>${safe(row.date)} ${safe(row.time)} • ${safe(row.subject)}</span><small>${safe(row.errors.join(', ')||row.server.email)}</small></div>`).join('');$('#importReservationsCsv').disabled=!csvRows.some(row=>!row.errors.length)};
  $('#importReservationsCsv').onclick=async()=>{const valid=csvRows.filter(row=>!row.errors.length),button=$('#importReservationsCsv'),lab=$('#csvReservationLab').value;if(!lab||!valid.length)return;button.disabled=true;let imported=0,failed=0;for(const row of valid){const {error}=await sb.rpc('staff_create_reservation',{p_server:row.server.id,p_lab:lab,p_subject:row.subject,p_start:localIso(row.date,row.time),p_blocks:1,p_notes:null,p_source:'CSV',p_recurrence:row.recurrence,p_until:row.until});error?failed++:imported++}button.disabled=false;modal('reservationCsvModal',false);toast(`${imported} linha(s) importada(s)${failed?`; ${failed} não importada(s) por conflito`:''}.`);await loadReservationAdmin()};

  loadPublicLabs();confirmFromLink();
})();
