(()=>{
  const sb=window.labinfoDb,$=selector=>document.querySelector(selector),safe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  if(!sb)return;
  const localIso=(date,time)=>new Date(`${date}T${time}:00-04:00`).toISOString(),localDate=value=>new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Cuiaba',dateStyle:'short'}).format(new Date(value)),localTime=value=>new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Cuiaba',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
  const normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
  function setupChoiceGroup(inputId){const input=$('#'+inputId),group=document.querySelector(`[data-choice-for="${inputId}"]`);if(!input||!group)return()=>{};const select=value=>{input.value=value;group.querySelectorAll('.choice-block').forEach(button=>{const active=button.dataset.value===String(value);button.classList.toggle('selected',active);button.setAttribute('aria-pressed',active)});input.dispatchEvent(new Event('change'))};group.querySelectorAll('.choice-block').forEach(button=>button.onclick=()=>select(button.dataset.value));select(input.value);return select}
  const periods=[['07:00','12:35'],['13:00','18:35'],['18:45','22:50']],times=[];
  const timeMinutes=value=>{const [hour,minute]=String(value||'').split(':').map(Number);return hour*60+minute};
  periods.forEach(([start,end])=>{let [hour,minute]=start.split(':').map(Number);while(hour*60+minute+45<=Number(end.slice(0,2))*60+Number(end.slice(3))){times.push(`${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`);minute+=45;hour+=Math.floor(minute/60);minute%=60}});
  $('#reservationTime').innerHTML='<option value="">Selecione o horário</option>'+times.map(time=>`<option value="${time}">${time}</option>`).join('');
  $('#reservationDate').min=new Date().toLocaleDateString('en-CA',{timeZone:'America/Cuiaba'});

  function showPublic(view,push=true){
    document.body.classList.remove('admin-route');$('#homeView').hidden=view!=='home';$('#reservationsPublicView').hidden=view!=='reservations';$('#teacherView').hidden=view!=='support';$('#adminView').hidden=true;
    if(push)history.pushState({},'',view==='home'?'/labinfo/':view==='reservations'?'/labinfo/reservas/':'/labinfo/suporte/');window.scrollTo(0,0);
  }
  $('#openReservations').onclick=()=>showPublic('reservations');$('#backHome').onclick=()=>showPublic('home');
  $('.brand').addEventListener('click',event=>{if(!$('#adminView').hidden)return;event.preventDefault();showPublic('home')});
  window.addEventListener('popstate',()=>{const path=location.pathname;if(path.includes('/reservas'))showPublic('reservations',false);else if(path.includes('/suporte'))showPublic('support',false);else if(!path.includes('/admin'))showPublic('home',false)});
  const initialPublicRoute=new URLSearchParams(location.search).get('route');if(location.pathname.includes('/reservas')||initialPublicRoute==='reservas'||new URLSearchParams(location.search).has('confirm_reservation'))showPublic('reservations',false);else if(location.pathname.includes('/suporte')||initialPublicRoute==='suporte')showPublic('support',false);

  let publicServer=null,publicLabs=[],publicScheduleRows=[],publicWeekStart=publicMonday(new Date());
  function publicMonday(value){const date=new Date(value);date.setHours(12,0,0,0);const day=date.getDay()||7;date.setDate(date.getDate()-day+1);return date}
  const publicIsoDate=date=>date.toLocaleDateString('en-CA',{timeZone:'America/Cuiaba'}),publicAddDays=(date,days)=>{const copy=new Date(date);copy.setDate(copy.getDate()+days);return copy};
  async function loadPublicLabs(){const {data,error}=await sb.from('labs').select('id,name,code').eq('active',true).order('name');if(error)return;publicLabs=data||[];const options=publicLabs.map(lab=>`<option value="${lab.id}">${safe(lab.name)}</option>`).join('');$('#reservationLab').innerHTML='<option value="">Selecione o laboratório</option>'+options;$('#publicScheduleLab').innerHTML=options;if(publicLabs.length)loadPublicSchedule()}
  async function loadPublicSchedule(){const lab=$('#publicScheduleLab').value||publicLabs[0]?.id;if(!lab)return;$('#publicScheduleLab').value=lab;const days=Array.from({length:6},(_,index)=>publicAddDays(publicWeekStart,index)),from=publicIsoDate(days[0]),to=publicIsoDate(days[5]),{data,error}=await sb.rpc('public_reservation_schedule',{p_lab:lab,p_from:from,p_to:to});if(error){$('#publicReservationSchedule').innerHTML=`<p class="empty error-text">${safe(error.message)}</p>`;return}publicScheduleRows=data||[];const scheduleTimes=[...new Set([...times,...publicScheduleRows.map(row=>localTime(row.starts_at))])].sort((a,b)=>timeMinutes(a)-timeMinutes(b));$('#publicScheduleWeek').textContent=`${localDate(days[0])} a ${localDate(days[5])}`;let html='<div class="calendar-corner">Horário</div>'+days.map(day=>`<div class="calendar-day"><strong>${day.toLocaleDateString('pt-BR',{weekday:'short'})}</strong><span>${day.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</span></div>`).join('');scheduleTimes.forEach(time=>{html+=`<div class="calendar-time">${time}</div>`;days.forEach(day=>{const date=publicIsoDate(day),items=publicScheduleRows.filter(row=>publicIsoDate(new Date(row.starts_at))===date&&localTime(row.starts_at)===time);html+=`<div class="calendar-cell public-calendar-cell ${items.length?'occupied-cell':'available-cell'}">${items.map(row=>`<article class="public-calendar-reservation ${row.status==='Autorizada'?'authorized':'pending'}"><strong>${safe(row.subject)}</strong>${row.server_name?`<span>${safe(row.server_name)}</span>`:''}<small>${localTime(row.starts_at)}–${localTime(row.ends_at)}</small></article>`).join('')}</div>`})});$('#publicReservationSchedule').innerHTML=html}
  $('#publicScheduleLab').onchange=loadPublicSchedule;$('#publicSchedulePrev').onclick=()=>{publicWeekStart=publicAddDays(publicWeekStart,-7);loadPublicSchedule()};$('#publicScheduleNext').onclick=()=>{publicWeekStart=publicAddDays(publicWeekStart,7);loadPublicSchedule()};
  let identityTimer;
  $('#reservationSiape').oninput=()=>{clearTimeout(identityTimer);publicServer=null;$('#reservationIdentity').textContent='Validando cadastro…';identityTimer=setTimeout(async()=>{const siape=$('#reservationSiape').value.trim();if(siape.length<5){$('#reservationIdentity').textContent='Digite seu SIAPE para validação.';return}const {data,error}=await sb.rpc('identify_server',{p_siape:siape});publicServer=data?.[0]||null;$('#reservationIdentity').textContent=error||!publicServer?'Servidor não localizado ou cadastro inativo.':`${publicServer.full_name} • ${publicServer.email}`;$('#reservationIdentity').className='field-hint '+(publicServer?'found':'pending')},350)};
  $('#reservationDate').onchange=()=>{const date=new Date($('#reservationDate').value+'T12:00:00');if(date.getDay()===0){$('#reservationDate').value='';toast('Os laboratórios não recebem reservas aos domingos.')}};
  const selectPublicBlocks=setupChoiceGroup('reservationBlocks'),selectPublicRecurrence=setupChoiceGroup('reservationRecurrence');$('#reservationRecurrence').onchange=()=>{const weekly=$('#reservationRecurrence').value==='weekly';$('#reservationUntilLabel').hidden=!weekly;$('#reservationUntil').required=weekly;$('#reservationUntil').min=$('#reservationDate').value};
  $('#publicReservationForm').onsubmit=async event=>{event.preventDefault();if(!publicServer)return toast('Valide um SIAPE cadastrado antes de continuar.');const button=event.submitter;button.disabled=true;button.textContent='Registrando solicitação…';try{const recurrence=$('#reservationRecurrence').value,{data,error}=await sb.rpc('create_public_reservation',{p_siape:$('#reservationSiape').value.trim(),p_lab:$('#reservationLab').value,p_subject:$('#reservationSubject').value.trim(),p_start:localIso($('#reservationDate').value,$('#reservationTime').value),p_blocks:Number($('#reservationBlocks').value),p_notes:$('#reservationNotes').value.trim()||null,p_recurrence:recurrence,p_until:recurrence==='weekly'?$('#reservationUntil').value:null});if(error)throw error;event.target.reset();selectPublicBlocks('1');selectPublicRecurrence('none');$('#reservationUntilLabel').hidden=true;publicServer=null;$('#reservationIdentity').textContent='Digite seu SIAPE para validação.';toast(`Solicitação ${data?.[0]?.protocol||''} registrada. Confirme pelo e-mail institucional.`)}catch(error){toast(error.message||'Não foi possível solicitar a reserva.')}finally{button.disabled=false;button.innerHTML='Solicitar reserva <span>→</span>'}};
  async function searchMyReservations(){const box=$('#myReservationsResult'),siape=$('#reservationSearchSiape').value.trim();box.innerHTML='<p class="empty">Consultando…</p>';const {data,error}=await sb.rpc('my_reservations',{p_siape:siape});if(error){box.innerHTML=`<p class="error-text">${safe(error.message)}</p>`;return}box.innerHTML=(data||[]).map(item=>`<article class="public-reservation-item"><header><strong>${safe(item.protocol)}</strong><span class="reservation-status status-${normalize(item.status).replace(/\s/g,'-')}">${safe(item.status)}</span></header><h3>${safe(item.subject)}</h3><p>${safe(item.lab)} • ${localDate(item.starts_at)}, ${localTime(item.starts_at)}–${localTime(item.ends_at)}</p>${item.reason?`<small>${safe(item.reason)}</small>`:''}</article>`).join('')||'<p class="empty">Nenhuma reserva encontrada para este SIAPE.</p>'}
  $('#searchReservations').onclick=searchMyReservations;$('#reservationSearchSiape').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();searchMyReservations()}};
  async function confirmFromLink(){const token=new URLSearchParams(location.search).get('confirm_reservation');if(!token)return;const box=$('#reservationConfirmation');box.hidden=false;box.innerHTML='<strong>Confirmando sua reserva…</strong>';const {data,error}=await sb.rpc('confirm_reservation',{p_token:token});box.innerHTML=error?`<strong>Não foi possível confirmar</strong><p>${safe(error.message)}</p>`:`<strong>✓ Reserva ${safe(data?.[0]?.protocol)} confirmada</strong><p>A solicitação foi encaminhada para autorização da equipe.</p>`;history.replaceState({},'',location.pathname)}

  const admin=$('#adminView');admin.insertAdjacentHTML('beforeend',`<section id="reservationsSection" class="admin-section reservations-admin" hidden>
    <div class="reservation-toolbar card"><div><button id="reservationPrevWeek" class="secondary" type="button">←</button><button id="reservationToday" class="secondary" type="button">Hoje</button><button id="reservationNextWeek" class="secondary" type="button">→</button><strong id="reservationWeekLabel"></strong></div><label>Laboratório<select id="adminReservationLab"></select></label><button id="newReservationButton" class="primary" type="button">+ Nova reserva</button><button id="csvReservationButton" class="secondary" type="button">Importar CSV</button></div>
    <div id="reservationStats" class="reservation-stats"></div><section class="card reservation-calendar-wrap"><div id="reservationCalendar" class="reservation-calendar"></div></section>
    <section class="card reservation-list-card"><div class="registry-head"><div><h2>Solicitações e reservas</h2><span id="reservationCount"></span></div><input id="reservationAdminSearch" placeholder="Buscar professor, disciplina ou protocolo"></div><div id="reservationAdminList"></div></section>
  </section>
  <div id="reservationModal" class="modal-backdrop" hidden><form id="staffReservationForm" class="modal card"><button class="modal-close" type="button" aria-label="Fechar">×</button><span class="eyebrow">NOVA RESERVA</span><h2>Cadastrar reserva</h2><label>Servidor<select id="staffReservationServer" required></select></label><label>Laboratório<select id="staffReservationLab" required></select></label><label>Disciplina ou atividade<input id="staffReservationSubject" maxlength="160" required></label><div class="field-row"><label>Data inicial<input id="staffReservationDate" type="date" required></label><label>Hora<select id="staffReservationTime" required></select></label></div><fieldset class="choice-field"><legend>Duração</legend><input id="staffReservationBlocks" type="hidden" value="1"><div class="choice-blocks duration-choices" data-choice-for="staffReservationBlocks"><button class="choice-block selected" type="button" data-value="1"><strong>1 bloco</strong><span>45 min</span></button><button class="choice-block" type="button" data-value="2"><strong>2 blocos</strong><span>1h30</span></button><button class="choice-block" type="button" data-value="3"><strong>3 blocos</strong><span>2h15</span></button><button class="choice-block" type="button" data-value="4"><strong>4 blocos</strong><span>3h</span></button></div></fieldset><div class="field-row recurrence-row"><fieldset class="choice-field"><legend>Repetição</legend><input id="staffReservationRecurrence" type="hidden" value="none"><div class="choice-blocks recurrence-choices" data-choice-for="staffReservationRecurrence"><button class="choice-block selected" type="button" data-value="none"><strong>Somente nesta data</strong></button><button class="choice-block" type="button" data-value="weekly"><strong>Semanalmente</strong><span>No mesmo dia da semana</span></button></div></fieldset><label id="staffReservationUntilLabel" hidden>Repetir até<input id="staffReservationUntil" type="date"></label></div><label>Observações<textarea id="staffReservationNotes" rows="3"></textarea></label><button class="primary" type="submit">Cadastrar e autorizar</button></form></div>
  <div id="reservationCsvModal" class="modal-backdrop" hidden><section class="modal card csv-reservation-modal" role="dialog" aria-modal="true" aria-labelledby="csvReservationTitle"><header class="csv-modal-head"><div><span class="eyebrow">IMPORTAÇÃO EM LOTE</span><h2 id="csvReservationTitle">Importar reservas por CSV</h2><p>Cadastre a grade recorrente do laboratório sem enviar notificações iniciais.</p></div><button class="modal-close" type="button" aria-label="Fechar">×</button></header><div class="csv-modal-body"><div class="csv-format-help"><strong>Formato esperado</strong><span>Data · Hora · Disciplina · Professor · Data fim · Recorrência</span><small>A data pode ser “Segunda-feira” e o horário “7:00 - 8:30”.</small></div><div class="field-row csv-settings"><label>Laboratório<select id="csvReservationLab" required></select></label><label>Início do semestre/lote<input id="csvReservationStart" type="date" required></label></div><label class="csv-file-field">Arquivo CSV<input id="reservationCsvFile" type="file" accept=".csv,text/csv"><small>Selecione um arquivo .csv para conferir os registros antes de importar.</small></label><div id="reservationCsvPreview" class="csv-preview-empty"><p>Nenhum arquivo selecionado.</p></div></div><footer class="csv-modal-footer"><div id="csvImportProgress" class="csv-import-progress" hidden><span>Preparando importação…</span><div><i></i></div></div><button id="importReservationsCsv" class="primary" type="button" disabled>Importar reservas válidas</button></footer></section></div>`);

  const reservationsMenuButton=$('#reservationsMenuButton');reservationsMenuButton.disabled=false;reservationsMenuButton.classList.remove('future-menu-button');reservationsMenuButton.removeAttribute('title');

  let reservations=[],adminLabs=[],adminServers=[],weekStart=getMonday(new Date()),draggedReservation=null,reservationChannel=null;
  function getMonday(value){const date=new Date(value);date.setHours(12,0,0,0);const day=date.getDay()||7;date.setDate(date.getDate()-day+1);return date}
  const isoDate=date=>date.toLocaleDateString('en-CA',{timeZone:'America/Cuiaba'}),addDays=(date,days)=>{const copy=new Date(date);copy.setDate(copy.getDate()+days);return copy};
  async function loadReservationAdmin(){const [{data:r,error},{data:l},{data:s}]=await Promise.all([sb.from('reservations').select('*,servers(full_name,siape,email),labs(name,code)').order('starts_at'),sb.from('labs').select('id,name,code').eq('active',true).order('name'),sb.from('servers').select('id,full_name,siape,email').eq('active',true).order('full_name')]);if(error)return toast(error.message);reservations=r||[];adminLabs=l||[];adminServers=s||[];fillAdminOptions();renderReservationAdmin()}
  function fillAdminOptions(){const labOptions=adminLabs.map(lab=>`<option value="${lab.id}">${safe(lab.name)}</option>`).join('');['adminReservationLab','staffReservationLab','csvReservationLab'].forEach(id=>{const element=$('#'+id),value=element.value;element.innerHTML=labOptions;if(value)element.value=value});$('#staffReservationServer').innerHTML=adminServers.map(server=>`<option value="${server.id}">${safe(server.full_name)} • ${safe(server.siape)}</option>`).join('');$('#staffReservationTime').innerHTML=times.map(time=>`<option value="${time}">${time}</option>`).join('')}
  function groupedReservations(){const groups=new Map;reservations.forEach(row=>{const key=row.recurrence_group||row.id;if(!groups.has(key))groups.set(key,{...row,occurrences:[],last_at:row.starts_at});const group=groups.get(key);group.occurrences.push(row);if(new Date(row.starts_at)>new Date(group.last_at))group.last_at=row.starts_at});return [...groups.values()]}
  function renderReservationAdmin(){renderCalendar();renderReservationList();const groups=groupedReservations(),counts={pending:groups.filter(r=>r.status.includes('Aguardando')).length,authorized:groups.filter(r=>r.status==='Autorizada').length,cancelled:groups.filter(r=>r.status==='Cancelada').length};$('#reservationStats').innerHTML=`<article><small>Aguardando</small><strong>${counts.pending}</strong></article><article><small>Autorizadas</small><strong>${counts.authorized}</strong></article><article><small>Canceladas</small><strong>${counts.cancelled}</strong></article>`}
  function renderCalendar(){const labId=$('#adminReservationLab').value||adminLabs[0]?.id;if(labId&&!$('#adminReservationLab').value)$('#adminReservationLab').value=labId;const days=Array.from({length:6},(_,index)=>addDays(weekStart,index)),weekRows=reservations.filter(r=>r.lab_id===labId&&r.status!=='Cancelada'&&new Date(r.starts_at)>=days[0]&&new Date(r.starts_at)<addDays(days[5],1)),scheduleTimes=[...new Set([...times,...weekRows.map(row=>localTime(row.starts_at))])].sort((a,b)=>timeMinutes(a)-timeMinutes(b));$('#reservationWeekLabel').textContent=`${localDate(days[0])} a ${localDate(days[5])}`;let html='<div class="calendar-corner">Horário</div>'+days.map(day=>`<div class="calendar-day"><strong>${day.toLocaleDateString('pt-BR',{weekday:'short'})}</strong><span>${day.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</span></div>`).join('');scheduleTimes.forEach(time=>{html+=`<div class="calendar-time">${time}</div>`;days.forEach(day=>{const date=isoDate(day),items=reservations.filter(r=>r.lab_id===labId&&r.status!=='Cancelada'&&isoDate(new Date(r.starts_at))===date&&localTime(r.starts_at)===time);html+=`<div class="calendar-cell" data-date="${date}" data-time="${time}">${items.map(r=>`<article class="calendar-reservation status-${normalize(r.status).replace(/\s/g,'-')}" draggable="true" data-id="${r.id}" title="Arraste para alterar data ou horário"><strong>${safe(r.subject)}</strong><span>${safe(r.servers?.full_name)}</span><small>${localTime(r.starts_at)}–${localTime(r.ends_at)}</small></article>`).join('')}</div>`})});$('#reservationCalendar').innerHTML=html;$('#reservationCalendar').querySelectorAll('.calendar-reservation').forEach(card=>card.ondragstart=()=>{draggedReservation=reservations.find(r=>r.id===card.dataset.id)});$('#reservationCalendar').querySelectorAll('.calendar-cell').forEach(cell=>{cell.ondragover=event=>{event.preventDefault();cell.classList.add('drag-over')};cell.ondragleave=()=>cell.classList.remove('drag-over');cell.ondrop=async event=>{event.preventDefault();cell.classList.remove('drag-over');if(!draggedReservation)return;const {error}=await sb.rpc('staff_update_reservation',{p_id:draggedReservation.id,p_start:localIso(cell.dataset.date,cell.dataset.time),p_lab:labId,p_status:null,p_reason:null});draggedReservation=null;if(error)return toast(error.message);toast('Reserva reagendada e servidor notificado.');await loadReservationAdmin()}})}
  function renderReservationList(){const query=normalize($('#reservationAdminSearch').value),rows=groupedReservations().filter(r=>!query||normalize([r.protocol,r.subject,r.servers?.full_name,r.labs?.name,r.status].join(' ')).includes(query));$('#reservationCount').textContent=`${rows.length} reserva(s)${reservations.length!==rows.length?` • ${reservations.length} ocorrências`:''}`;$('#reservationAdminList').innerHTML=rows.map(r=>{const recurring=r.occurrences.length>1,period=recurring?`${localDate(r.starts_at)} a ${localDate(r.last_at)} • ${r.occurrences.length} semanas`:`${localDate(r.starts_at)}, ${localTime(r.starts_at)}–${localTime(r.ends_at)}`;return `<article class="reservation-admin-row"><div><span class="ticket-id">${safe(r.protocol)}${recurring?' • RECORRENTE':''}</span><h3>${safe(r.subject)}</h3><p>${safe(r.servers?.full_name)} • ${safe(r.labs?.name)} • ${period}</p></div><span class="reservation-status status-${normalize(r.status).replace(/\s/g,'-')}">${safe(r.status)}</span><div class="reservation-row-actions">${!recurring&&r.status==='Aguardando autorização'?`<button data-approve="${r.id}">Autorizar</button>`:''}${!recurring&&r.status!=='Cancelada'?`<button data-cancel="${r.id}">Cancelar</button>`:''}</div></article>`}).join('')||'<p class="empty">Nenhuma reserva encontrada.</p>';$('#reservationAdminList').querySelectorAll('[data-approve]').forEach(button=>button.onclick=()=>updateStatus(button.dataset.approve,'Autorizada'));$('#reservationAdminList').querySelectorAll('[data-cancel]').forEach(button=>button.onclick=()=>{const reason=prompt('Informe o motivo do cancelamento:');if(reason)updateStatus(button.dataset.cancel,'Cancelada',reason)})}
  async function updateStatus(id,status,reason=null){const {error}=await sb.rpc('staff_update_reservation',{p_id:id,p_start:null,p_lab:null,p_status:status,p_reason:reason});if(error)return toast(error.message);toast(status==='Autorizada'?'Reserva autorizada e servidor notificado.':'Reserva cancelada e servidor notificado.');await loadReservationAdmin()}
  async function openReservationsAdmin(){document.querySelectorAll('.admin-section').forEach(section=>section.hidden=true);$('#reservationsSection').hidden=false;$('#adminTitle').textContent='Reservas dos laboratórios';$('#adminSubtitle').textContent='Organize a agenda, autorize solicitações e importe reservas em lote.';await loadReservationAdmin();if(!reservationChannel)reservationChannel=sb.channel('labinfo-reservations').on('postgres_changes',{event:'*',schema:'public',table:'reservations'},()=>loadReservationAdmin()).subscribe()}
  reservationsMenuButton.onclick=openReservationsAdmin;$('#adminReservationLab').onchange=renderCalendar;$('#reservationAdminSearch').oninput=renderReservationList;$('#reservationPrevWeek').onclick=()=>{weekStart=addDays(weekStart,-7);renderCalendar()};$('#reservationNextWeek').onclick=()=>{weekStart=addDays(weekStart,7);renderCalendar()};$('#reservationToday').onclick=()=>{weekStart=getMonday(new Date());renderCalendar()};
  function modal(id,open){$('#'+id).hidden=!open;document.body.classList.toggle('modal-open',open)}
  $('#newReservationButton').onclick=()=>modal('reservationModal',true);$('#csvReservationButton').onclick=()=>{if(!$('#csvReservationStart').value)$('#csvReservationStart').value=isoDate(getMonday(new Date()));modal('reservationCsvModal',true)};document.querySelectorAll('#reservationModal .modal-close,#reservationCsvModal .modal-close').forEach(button=>button.onclick=()=>modal(button.closest('.modal-backdrop').id,false));
  const selectStaffBlocks=setupChoiceGroup('staffReservationBlocks'),selectStaffRecurrence=setupChoiceGroup('staffReservationRecurrence');$('#staffReservationRecurrence').onchange=()=>{const weekly=$('#staffReservationRecurrence').value==='weekly';$('#staffReservationUntilLabel').hidden=!weekly;$('#staffReservationUntil').required=weekly;$('#staffReservationUntil').min=$('#staffReservationDate').value};
  $('#staffReservationForm').onsubmit=async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{const recurrence=$('#staffReservationRecurrence').value,{data:created,error}=await sb.rpc('staff_create_reservation',{p_server:$('#staffReservationServer').value,p_lab:$('#staffReservationLab').value,p_subject:$('#staffReservationSubject').value.trim(),p_start:localIso($('#staffReservationDate').value,$('#staffReservationTime').value),p_blocks:Number($('#staffReservationBlocks').value),p_notes:$('#staffReservationNotes').value.trim()||null,p_source:'Equipe',p_recurrence:recurrence,p_until:recurrence==='weekly'?$('#staffReservationUntil').value:null});if(error)throw error;const notification=await sb.rpc('staff_update_reservation',{p_id:created.id,p_start:null,p_lab:null,p_status:'Autorizada',p_reason:null});if(notification.error)throw notification.error;event.target.reset();selectStaffBlocks('1');selectStaffRecurrence('none');$('#staffReservationUntilLabel').hidden=true;modal('reservationModal',false);toast('Reserva cadastrada, autorizada e servidor notificado.');await loadReservationAdmin()}catch(error){toast(error.message)}finally{button.disabled=false}};
  let csvRows=[];
  function parseCsvDate(value){const clean=String(value||'').trim();if(/^\d{4}-\d{2}-\d{2}$/.test(clean))return clean;const match=clean.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);return match?`${match[3]}-${match[2].padStart(2,'0')}-${match[1].padStart(2,'0')}`:''}
  function firstWeekdayOnOrAfter(start,weekday){if(!start)return '';const date=new Date(`${start}T12:00:00`);if(Number.isNaN(date.getTime()))return '';date.setDate(date.getDate()+(weekday-date.getDay()+7)%7);return isoDate(date)}
  function matchCsvServer(name){const wanted=normalize(name).split(/\s+/).filter(Boolean),matches=adminServers.filter(server=>{const available=normalize(server.full_name).split(/\s+/);return wanted.length&&wanted.every(token=>available.includes(token))});return matches.length===1?matches[0]:null}
  function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(line=>line.trim()),delimiter=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',';const cells=line=>line.split(delimiter).map(value=>value.trim().replace(/^"|"$/g,'')),headers=cells(lines.shift()).map(normalize),weekdays={domingo:0,segunda:1,terca:2,quarta:3,quinta:4,sexta:5,sabado:6},semesterStart=$('#csvReservationStart').value;return lines.map((line,index)=>{const values=cells(line),get=name=>{const position=headers.indexOf(name);return position<0?'':values[position]||''},professor=get('professor')||get('nome completo')||get('nome'),server=matchCsvServer(professor),dateRaw=get('data'),weekdayName=normalize(dateRaw).replace(/\s*-?feira\s*/g,''),weekday=weekdays[weekdayName],date=weekday===undefined?parseCsvDate(dateRaw):firstWeekdayOnOrAfter(semesterStart,weekday),untilRaw=get('data fim')||get('fim'),until=untilRaw?parseCsvDate(untilRaw):null,recurrence=weekday!==undefined||normalize(get('recorrencia'))==='semanal'||!!until?'weekly':'none',timeRaw=get('hora')||get('horario'),range=timeRaw.match(/^(\d{1,2}):(\d{2})\s*[-–—]\s*(\d{1,2}):(\d{2})$/),single=timeRaw.match(/^(\d{1,2}):(\d{2})$/),timeMatch=range||single,time=timeMatch?`${timeMatch[1].padStart(2,'0')}:${timeMatch[2]}`:'',duration=range?(Number(range[3])*60+Number(range[4]))-(Number(range[1])*60+Number(range[2])):45,blocks=duration>0&&duration%45===0?duration/45:0,subject=get('disciplina')||get('atividade'),errors=[];if(!server)errors.push('Professor não cadastrado ou nome ambíguo');if(weekday!==undefined&&!semesterStart)errors.push('Informe o início do semestre/lote');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))errors.push('Data inválida');if(recurrence==='weekly'&&!/^\d{4}-\d{2}-\d{2}$/.test(until||''))errors.push('Data final inválida');if(until&&date&&until<date)errors.push('Data final anterior ao início');if(!time||!blocks)errors.push('Horário ou duração inválida');if(!subject)errors.push('Disciplina ausente');return {line:index+2,date,dateRaw,until,recurrence,time,timeRaw,blocks,subject,professor,server,errors}})}
  async function previewCsv(){const file=$('#reservationCsvFile').files[0];if(!file)return;csvRows=parseCsv(await file.text());const preview=$('#reservationCsvPreview');preview.classList.remove('csv-preview-empty');preview.innerHTML=`<div class="csv-summary"><strong>${csvRows.filter(row=>!row.errors.length).length} válida(s)</strong><span>${csvRows.filter(row=>row.errors.length).length} com erro</span></div>`+csvRows.slice(0,50).map(row=>`<div class="csv-row ${row.errors.length?'invalid':''}"><span>Linha ${row.line}</span><strong>${safe(row.professor)}</strong><span>${safe(row.dateRaw)} → ${safe(row.date)} • ${safe(row.timeRaw)} • ${safe(row.subject)}</span><small>${safe(row.errors.join(', ')||row.server.email)}</small></div>`).join('');$('#importReservationsCsv').disabled=!csvRows.some(row=>!row.errors.length)}
  const previewCsvAndFocusWeek=async()=>{await previewCsv();const first=csvRows.filter(row=>!row.errors.length).map(row=>row.date).sort()[0];if(first)weekStart=getMonday(new Date(`${first}T12:00:00`))};$('#reservationCsvFile').onchange=previewCsvAndFocusWeek;$('#csvReservationStart').onchange=previewCsvAndFocusWeek;
  $('#importReservationsCsv').onclick=async()=>{const valid=csvRows.filter(row=>!row.errors.length),button=$('#importReservationsCsv'),lab=$('#csvReservationLab').value,progress=$('#csvImportProgress');if(!lab)return toast('Selecione o laboratório deste lote.');if(!valid.length)return toast('Não há linhas válidas para importar.');if(button.dataset.running==='true')return;button.dataset.running='true';button.disabled=true;button.textContent='Importando…';progress.hidden=false;let imported=0,failed=0;const failures=[];try{for(let index=0;index<valid.length;index++){const row=valid[index],percent=Math.round(index/valid.length*100);progress.querySelector('span').textContent=`Importando ${index+1} de ${valid.length}: ${row.professor}`;progress.querySelector('i').style.width=percent+'%';await new Promise(resolve=>requestAnimationFrame(resolve));try{const {error}=await sb.rpc('staff_create_reservation',{p_server:row.server.id,p_lab:lab,p_subject:row.subject,p_start:localIso(row.date,row.time),p_blocks:row.blocks,p_notes:null,p_source:'CSV',p_recurrence:row.recurrence,p_until:row.until});if(error){failed++;failures.push(`Linha ${row.line}: ${error.message}`)}else imported++}catch(error){failed++;failures.push(`Linha ${row.line}: ${error.message||'falha inesperada'}`)}}progress.querySelector('i').style.width='100%';progress.querySelector('span').textContent=`Concluído: ${imported} importada(s), ${failed} não importada(s).`;await loadReservationAdmin();if(failures.length){$('#reservationCsvPreview').insertAdjacentHTML('afterbegin',`<div class="csv-import-errors"><strong>Linhas não importadas</strong>${failures.slice(0,12).map(message=>`<span>${safe(message)}</span>`).join('')}</div>`)}if(imported){toast(`${imported} linha(s) importada(s)${failed?`; ${failed} não importada(s)`:''}.`);if(!failed)setTimeout(()=>modal('reservationCsvModal',false),700)}else toast('Nenhuma reserva foi importada. Consulte os erros exibidos.')}catch(error){progress.querySelector('span').textContent='A importação foi interrompida.';toast(error.message||'Não foi possível concluir a importação.')}finally{button.dataset.running='false';button.disabled=false;button.textContent=failed?'Tentar importar novamente':'Importar reservas válidas'}};

  loadPublicLabs();confirmFromLink();
})();
